
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  postgres_checkout:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_CHECKOUT_DB}
      POSTGRES_USER: ${POSTGRES_CHECKOUT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CHECKOUT_PASSWORD}
    volumes:
      - checkout_data:/var/lib/postgresql/data

  postgres_payments:
    image: postgres:16
    ports:
      - "5434:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_PAYMENTS_DB}
      POSTGRES_USER: ${POSTGRES_PAYMENTS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PAYMENTS_PASSWORD}
    volumes:
      - payments_data:/var/lib/postgresql/data

  postgres_expedition:
    image: postgres:16
    ports:
      - "5435:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_EXPEDITION_DB}
      POSTGRES_USER: ${POSTGRES_EXPEDITION_USER}
      POSTGRES_PASSWORD: ${POSTGRES_EXPEDITION_PASSWORD}
    volumes:
      - expedition_data:/var/lib/postgresql/data

  checkout:
    build:
      context: ./checkout
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
      - postgres_checkout
    env_file:
      - .env.dev
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DATABASE_URL: ${POSTGRES_CHECKOUT_URL}

  payments:
    build:
      context: ./payments
    ports:
      - "3002:3000"
    depends_on:
      - rabbitmq
      - postgres_payments
    env_file:
      - .env.dev
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DATABASE_URL: ${POSTGRES_PAYMENTS_URL}

  expedition:
    build:
      context: ./expedition
    ports:
      - "3003:3000"
    depends_on:
      - rabbitmq
      - postgres_expedition
    env_file:
      - .env.dev
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      DATABASE_URL: ${POSTGRES_EXPEDITION_URL}

  bff:
    build:
      context: ./bff
    ports:
      - "3000:3000"
    depends_on:
      checkout:
        condition: service_started
      expedition:
        condition: service_started
      payments:
        condition: service_started
    env_file:
      - .env.dev
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}

volumes:
  checkout_data:
  payments_data:
  expedition_data:
